### ISSUE TITLE
Featured image meta box

### ISSUE THREAD

**Issue by stevegrunwell** [10up/SwiftStream#3] opened 2015-01-28 15:34 UTC
It would be helpful if either the featured image meta box loaded the higher-res version of the image or SwiftStream was triggered on the post edit screen to avoid things like this (which was jarring before I realized the site where I was seeing it was one that was using SwiftStream):

![low-res-featured-image](https://cloud.githubusercontent.com/assets/233836/5940484/28956c6a-a6d9-11e4-8c96-08cf8e920403.png)

**Comment by ericmann** [comment] 2015-05-25 01:32
The functionality that loads the pixelated placeholder has an `is_admin()` check to prevent this. Closing for now as I can't reproduce.

**Closed by ericmann** 2015-05-25 01:32 UTC
